TUTORIAL - 0

1. TensorFlow: TensorFlow is an open-source, end-to-end platform by Google for building and deploying machine learning (ML) and Artificial Intelligence (AI) models, using data flow graphs (tensors) for numerical computation, especially deep neural networks



The Python packages Numpy, which stands for "Numerical Python"

Q. Find difference between python list and numpy array

In [1]:
print('Hello, World')

Hello, World


In [2]:
# Q1. Import numpy library.

import numpy as np

In [3]:
print(np.__version__)

2.2.6


In [4]:
# Q2. Create 1D array with 5 elements.

l1 = [1,2,3,4,5]
x = np.array(l1)
x

array([1, 2, 3, 4, 5])

In [5]:
x.dtype

dtype('int64')

In [6]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [7]:
# Q3. Create 1D array with 5 elements random value. (by default values between 0 to 1)

x = np.random.rand(5)
x

array([0.38856459, 0.93947778, 0.55194408, 0.4590164 , 0.62699532])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
# Q4. Generate random value from range 5 to 15 with 1D array size 10.

x = np.random.randint(5,16,10)
x

array([15,  9, 11, 10,  7, 15,  7, 15, 11, 15], dtype=int32)

In [11]:
# Q5. Create 2D array - 4 by 3 size.
y = np.array([[2,3,4],[4,5,6],[5,6,7],[7,8,9]])
print(y)

[[2 3 4]
 [4 5 6]
 [5 6 7]
 [7 8 9]]


In [12]:
# Q6. Create 2D array with size 3 by 3. Elements values are random number(by default values between 0 to 1)

np.random.rand(3,3)

array([[0.01322868, 0.82428469, 0.91814415],
       [0.56972699, 0.68913796, 0.40253269],
       [0.78098115, 0.12237389, 0.57777273]])

In [13]:
# Q7. Generate random value from range 5 to 15 with 2D array size 3 by 3.

np.random.randint(5,16,(3,3))

array([[ 5, 14,  7],
       [15, 11, 12],
       [10,  6, 12]], dtype=int32)

In [14]:
# Q8. Create 3D array with size 2 * 3 * 2.

z = np.array([[[1,2,3],[4,5,6]],[[3,4,5],[6,7,8]]])
print(z)

[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [6 7 8]]]


In [15]:
# Q9. Initialize 5 by 5 array with all values are zeros.

a = np.zeros((5,5), dtype=int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [16]:
# Q10. Initialize 5 by 5 array with all values are ones.

a = np.ones((5,5), dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
# Q11. Initialize 5 by 5 array with all values are particular values(consider 4).

a = np.full((5,5),2)
print(a)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [18]:
a = np.full((5,5),5)
print(a)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [19]:
# Q12. Create indentity matrix with all diagonal values are 1 and rest all values are zeros.

a = np.eye(3,3) * 5
print(a)

[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


In [20]:
a.dtype

dtype('float64')

In [21]:
a.size

9

In [22]:
x.size

10

In [23]:
y.size

12

In [24]:
x.ndim

1

In [25]:
a.ndim

2

In [26]:
z.ndim

3

In [27]:
a.shape

(3, 3)

In [28]:
z.shape

(2, 2, 3)

In [29]:
y.shape

(4, 3)

In [30]:
print(x)

[15  9 11 10  7 15  7 15 11 15]


In [31]:
x.min()

np.int32(7)

In [32]:
x.max()

np.int32(15)

In [33]:
x.mean()

np.float64(11.5)

In [34]:
x.argmin()

np.int64(4)

In [35]:
y.argmin()

np.int64(0)

In [36]:
z.argmin()

np.int64(0)

In [37]:
z.argmax()

np.int64(11)

In [38]:
x.argmax()

np.int64(0)

In [39]:
# Q21. Create two 2D array of size 3 by 3 and perform four basic mathematical operations.

x = np.random.randint(5,16,(3,3))
y = np.random.randint(1,7,(3,3))

print(x+y)

[[10 18  8]
 [18 15 15]
 [ 9 11 15]]


In [40]:
print(x-y)

[[ 6  8  2]
 [ 6  5  9]
 [ 1  3 11]]


In [41]:
print(x*y)

[[16 65 15]
 [72 50 36]
 [20 28 26]]


In [42]:
print(x/y)

[[4.         2.6        1.66666667]
 [2.         2.         4.        ]
 [1.25       1.75       6.5       ]]


In [43]:
np.add(x,y)

array([[10, 18,  8],
       [18, 15, 15],
       [ 9, 11, 15]], dtype=int32)

In [44]:
np.subtract(x,y)

array([[ 6,  8,  2],
       [ 6,  5,  9],
       [ 1,  3, 11]], dtype=int32)

In [ ]:
np.multiply(x,y)

array([[16, 65, 15],
       [72, 50, 36],
       [20, 28, 26]], dtype=int32)

In [46]:
np.divide(x,y)

array([[4.        , 2.6       , 1.66666667],
       [2.        , 2.        , 4.        ],
       [1.25      , 1.75      , 6.5       ]])

In [47]:
np.divide(y,x)

array([[0.25      , 0.38461538, 0.6       ],
       [0.5       , 0.5       , 0.25      ],
       [0.8       , 0.57142857, 0.15384615]])

- Indexing is used to access a single element from a sequence using its pesition ir index

- It retrives a single element as a specific position.

- Python used zero-based indexing (0 is the first element).

- Negative indexing allows access from the end of structure.

In [48]:
# Q22. Print index 2 and -2 value for 1D array. (indexing).

x= np.array([2,4,7,2,0,9,6,8])
x

array([2, 4, 7, 2, 0, 9, 6, 8])

In [49]:
x[2]

np.int64(7)

In [50]:
x[-2]

np.int64(6)

In [51]:
y

array([[2, 5, 3],
       [6, 5, 3],
       [4, 4, 2]], dtype=int32)

In [52]:
y[2,2]

np.int32(2)

In [53]:
y[0,1]

np.int32(5)

Slicing 

Q. Find the difference b/w indexing & Slicing

In [54]:
x[:]

array([2, 4, 7, 2, 0, 9, 6, 8])

In [55]:
x[:5]

array([2, 4, 7, 2, 0])

In [56]:
x[5:]

array([9, 6, 8])

In [57]:
x[2:5]

array([7, 2, 0])

In [58]:
x[2:5] = 19

In [59]:
x

array([ 2,  4, 19, 19, 19,  9,  6,  8])

In [60]:
x[:] = 100
x

array([100, 100, 100, 100, 100, 100, 100, 100])

In [61]:
x = np.array([5,6,9,0,12,45,3,89])
np.flip(x)

array([89,  3, 45, 12,  0,  9,  6,  5])

In [62]:
x

array([ 5,  6,  9,  0, 12, 45,  3, 89])

In [63]:
x = np.flip(x)
x

array([89,  3, 45, 12,  0,  9,  6,  5])