Find a suitable dataset for unsupervised learning that contains at least 1000 instances and 5 features. Implement any two appropriate unsupervised learning algorithms on the chosen dataset. Evaluate and compare the performance of both algorithms using suitable metrics, and determine which algorithm performs better for the given dataset.

In [2]:
# Step 1: Import Libraries
import pandas as pd
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

# Step 2: Load Dataset
df = pd.read_csv("Datasets/winequality-red.csv")

# Step 3: Select Features
X = df[['fixed acidity','volatile acidity','citric acid','residual sugar','alcohol']]

# Step 4: Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 5: K-Means
kmeans = KMeans(n_clusters=5, random_state=42)
k_labels = kmeans.fit_predict(X_scaled)
k_score = silhouette_score(X_scaled, k_labels)

# Step 6: Hierarchical Clustering
hc = AgglomerativeClustering(n_clusters=5)
h_labels = hc.fit_predict(X_scaled)
h_score = silhouette_score(X_scaled, h_labels)

# Step 7: Results
print("K-Means Score:", k_score)
print("Hierarchical Score:", h_score)

K-Means Score: 0.23424190315347032
Hierarchical Score: 0.17926874861530087


In [5]:
import pandas as pd 
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

df = pd.read_csv("Datasets/winequality-red.csv")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5


In [6]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

# Load Dataset
df = pd.read_csv("Datasets/winequality-red.csv")

# Select Features
X = df[['fixed acidity','volatile acidity','citric acid','residual sugar','alcohol']]

# Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# K-Means Model
kmeans = KMeans(n_clusters=5, random_state=42)
labels = kmeans.fit_predict(X_scaled)

# Evaluation
score = silhouette_score(X_scaled, labels)

print("K-Means Score:", score)

K-Means Score: 0.23424190315347032


In [7]:
import pandas as pd
from sklearn.cluster import AgglomerativeClustering
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

# Load Dataset
df = pd.read_csv("Datasets/winequality-red.csv")

# Select Features
X = df[['fixed acidity','volatile acidity','citric acid','residual sugar','alcohol']]

# Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Hierarchical Model
hc = AgglomerativeClustering(n_clusters=5)
labels = hc.fit_predict(X_scaled)

# Evaluation
score = silhouette_score(X_scaled, labels)

print("Hierarchical Score:", score)

Hierarchical Score: 0.17926874861530087


In [11]:
import pandas as pd

df = pd.read_csv("Datasets/winequality-red.csv")

print("Dataset Shape:", df.shape)


Dataset Shape: (1596, 12)


In [12]:
X = df[['fixed acidity','volatile acidity','citric acid','residual sugar','alcohol']]

print("\nSelected Features:\n", X.head())


Selected Features:
    fixed acidity  volatile acidity  citric acid  residual sugar  alcohol
0            7.4              0.70         0.00             1.9      9.4
1            7.8              0.88         0.00             2.6      9.8
2            7.8              0.76         0.04             2.3      9.8
3           11.2              0.28         0.56             1.9      9.8
4            7.4              0.70         0.00             1.9      9.4


In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("\nScaled Data Sample:\n", X_scaled[:5])


Scaled Data Sample:
 [[-0.52790985  0.96050573 -1.3943694  -0.4523301  -0.96331098]
 [-0.29691763  1.9654189  -1.3943694   0.045864   -0.58596616]
 [-0.29691763  1.29547678 -1.18800687 -0.16764775 -0.58596616]
 [ 1.66651622 -1.38429169  1.49470607 -0.4523301  -0.58596616]
 [-0.52790985  0.96050573 -1.3943694  -0.4523301  -0.96331098]]


In [14]:
print("\n===== FINAL COMPARISON =====")

if k_score > h_score:
    print("Best Algorithm: K-Means")
else:
    print("Best Algorithm: Hierarchical")


===== FINAL COMPARISON =====
Best Algorithm: K-Means


In [15]:
from sklearn.metrics import accuracy_score
import numpy as np

# Actual labels
y_true = df['quality']

# Convert cluster labels to match classes (simple mapping)
# (cluster numbers ko classes ke equal range me lana)
k_labels_adj = k_labels % len(np.unique(y_true))

# Accuracy
accuracy = accuracy_score(y_true, k_labels_adj)

print("Approx Accuracy (K-Means):", round(accuracy, 3))

Approx Accuracy (K-Means): 0.001
